### ISSUE TITLE
Bad path on Windows

### ISSUE THREAD

**Issue by artursudnik** [mila-labs/express-asset-versions#1]
# {asset('/stylesheets/reset.css')}

results in rendering:

\public\stylesheets\reset.css?18e1bcf910

**Comment by mweibel** [comment]
This could be because of this:
https://github.com/mila-labs/express-asset-versions/blob/master/index.js#L14

Not sure though, what do you think @pstadler? 
You could try what happens if you replace `\` with `/` before _writing_.

**Comment by pstadler** [comment]
Will have a look in the next days.

**Comment by pstadler** [comment]
Please upgrade to 0.1.2 and repoen the issue if this is still a problem :+1:
